### ISSUE TITLE
the console closes automatically without opening the browser

### ISSUE THREAD

**Issue by Abybachir5** [SuCicada/lain-voice-models#1]
the console closes automatically without opening the browser
[https://www.youtube.com/watch?v=66AJ4X0r0IM](url)

**Comment by SuCicada** [comment]
Thank you for your attention to my project.
I think this is the same question with https://github.com/SuCicada/lain-voice-models/issues/2
I made a mistake sorry

now I have updated the code. https://github.com/SuCicada/lain-voice-models/commit/571c5107180b37d78870b2ff01582c7408e302e7

you just need re-download the [lain-voice.bat](https://raw.githubusercontent.com/SuCicada/lain-voice-models/master/lain-voice.bat) and replace the last one

please try it. If you still have questions, please contact me

**Comment by Abybachir5** [comment]
thanks, but the error was in another. The bat file didn't want to work because the folder it was in was called Lain voise(according to the tutorial, the folder in which all files should be located should have any name), but when I changed the name of the folder to Lain, it worked. So in the guide you need to write that a person creates a folder with a certain name, and not any

**Comment by Abybachir5** [comment]
I think it's better to archive the folder with all the files and put it out so that there are no unnecessary problems

**Comment by SuCicada** [comment]
This problem is because the path has space. I will fix it.
But you are right. it's better to archive the folder with all the files

I started it so that you don’t need to re-download when you upgrade later
But now it looks like I may not be updating this anytime soon（Although I really want to update, I am tired recently）
